---
- hosts: all
  become: yes
  tasks:


    # Instalacion de git
    - name: Instala git
      apt: pkg=git state=present


    # Clonamos Repositorio
    - name: Clonar nuestro repositorio en github
      git:
        repo: https://github.com/juaneml/IV_1819_Proyecto.git
        dest: iv1819proyecto/


    # Instalación de  Python 3

    # Repositorios necesarios para python3
    - name: repositorios necesario deadsnakes PPA python3
      apt_repository: repo=ppa:deadsnakes/ppa state=present

    #Actualzamos repositorio
    - name: update repositorio
      command: sudo apt-get update

    #Instalamos python3
    - name: Instalación python3
      apt: pkg=python3.6 state=present


  # Instalamos pip3

    - name: Instalación pip3
      apt: pkg=python3-pip state=latest

  # Instalamos Requirements necesarios para nuestro microservicio

    - name: Install requirements.txt
      command: pip3 install -r ./iv1819proyecto/requirements.txt
