---
- hosts: all
  become: yes
  tasks:


    # Instalacion de git
    - name: Instala git
      apt: pkg=git state=present


    # Clonamos Repositorio

    - name: Clonar nuestro repositorio en github
      git:
        repo: https://github.com/juaneml/IV_1819_Proyecto.git
        dest: iv1819proyecto/
      become: no


    # Instalación de  Python 3

    # Repositorios necesarios para python3

    - name: repositorios necesario deadsnakes PPA python3
      apt_repository: repo=ppa:deadsnakes/ppa state=present

      become: yes

    #Actualizamos repositorios

    - name: update repositorio
      apt:
        update_cache: yes
      become: yes

    #upgrade repositorios
    - name: upgrade all packets to the last version
      apt:
        upgrade: dist
      become: yes
    #Instalamos python3

    - name: Instalación python3
      apt: pkg=python3.6 state=present
      become: yes


  # Instalamos pip3

    - name: Instalación pip3
      apt: pkg=python3-pip state=latest

      become: yes

  # Instalamos Requirements necesarios para nuestro microservicio

    - name: Install requirements.txt
      command: pip3 install -r ./iv1819proyecto/requirements.txt

      become: yes
