language: python

python:
  - "3.6.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install hug -U

# command to run tests
script: cd ./test && pytest
  #- make test
